### ISSUE TITLE
Error Running Code

### ISSUE THREAD

**Issue by tvuong123** [jotaf98/curveball#1]
I'm trying to run the sample scripts 'training('basic-curveball', 'solver',CurveBall(), 'learningRate',1)'

I fixed all of the matcovnet and autonn issues but now I'm getting this error.  Does this have something to do with the dataset?
<img width="566" alt="screen shot 2018-09-26 at 8 46 13 pm" src="https://user-images.githubusercontent.com/32756684/46117096-3ff0c400-c1cd-11e8-94bc-73a971f1dfe7.png">

**Comment by tvuong123** [comment]
Also says this
Attempt to execute SCRIPT vl_nnconv as a function:

**Comment by albanie** [comment]
Hi @tvuong123, usually the last error is a path ordering issue (it tends to mean that the matlab script is higher up the path than the compiled convolution layers).  If you re-run `vl_setupnn`, and then run `vl_nnconv(1,1,1)`, do you still get the same error?

**Comment by tvuong123** [comment]
Ok I decided to recompile it. vl_nnconv(1,1,1) gives me no errors but now I get a new error when I try running the test scripts 
<img width="691" alt="screen shot 2018-09-28 at 4 33 37 pm" src="https://user-images.githubusercontent.com/32756684/46232183-55383080-c33c-11e8-9bfa-7cf47aac583f.png">

**Comment by tvuong123** [comment]
NVM.  I think i found the issue. it says CPU mode is not yet supported for fmad bnorm

**Comment by jotaf98** [comment]
Yes we didn't replicate the CUDA code for pure CPU mode. But the error message could be more descriptive! I just updated it.
