### ISSUE TITLE
Bug in line 292 of CurveBall.m

### ISSUE THREAD

**Issue by Yolanda-Gao** [jotaf98/curveball#3]
I was running the first example: training('basic-curveball', 'solver',CurveBall(), 'learningRate',1)

It shows that matrix dimension doesn't match. I checked and found px and x are not the same dimension. 
According to the paper, we are trying to compute Hlx = p. * x - p * p' * x;  The former codes to compute px doesn't seem to a right matrix multiplication to compute p'*x 

I changed the code accordingly and I can run the experiments now. 

Am I doing the right thing?

**Comment by hyenal** [comment]
Thanks for reporting the issue. I have ran the code successfully and I would like to know what is your matconvnet setup ? What is the error without your bug fix ?

**Comment by Yolanda-Gao** [comment]
The error is:

> In training (line 49)
Error using .*
Matrix dimensions must agree.

>Error in CurveBall>hessian_grad_loss (line 292)
    Hlx = p .* x - p .* px;

>Error in CurveBall/gradientStep (line 88)
      [Jz_, Jl, o.last_loss] = hessian_grad_loss(net, o.loss, o.labels, Jz);

>Error in solvers.Solver/step (line 108)
      w(is_grad) = o.gradientStep(w(is_grad), dw(is_grad), lr(is_grad), decay(is_grad)) ;

>Error in training (line 197)
        solver.step(net);

My matconvnet setup is matlab2016a with CUDA 8.0 using the unsupported CUDA toolkit setup method by specifying the cuda location.

**Comment by hyenal** [comment]
I assume you are also using cudnn? Are you using the latest matconvnet and autonn? In any case can you also post the code of the hot fix you did ?

**Comment by Yolanda-Gao** [comment]
I didn't use cudnn when I compiled matconvnet. Yes, I used the most recent master branch cloned from matconvnet and autonn. 

The fix I did is:
> Hlx = zeros(size(x), 'gpuArray');
ptmp = squeeze(p);
xtmp = squeeze(x);
Hlx(1,1,:,:)=ptmp.xtmp-ptmpptmp'*xtmp;

But after the change, I got warnings of singular matrix and badly scaled matrix and my training error didn't drop much. 

I don't think the former code:
> if ismatrix(p)
px = sum(p .* x, 1);
else % 4D tensor
px = sum(p .* x, 3);
end

is the right matrix multiplication of 'p'*x'?

**Comment by hyenal** [comment]
The formula you mentioned is actually valid for a single sample. So for a single sample you will define  Hlx as Hlx = p. * x - p * p' * x but not for the entire batch (you will mix probabilities in this case). I will update the comments so to clarify. I tried a temporary fix which works fine:
```
    p = vl_nnsoftmax(pred);  % softmaxed probabilities
    Hlx = zeros(size(x), 'gpuArray');
    ptmp = squeeze(p);
    xtmp = squeeze(x);
    if ismatrix(p)
      px = sum(p .* x, 1);
    else  % 4D tensor
      px = sum(p .* x, 3);
    end
    %% now finish computing Hl * x = diag(p) * x - p * p' * x
    Hlx(1,1,:,:) = p .* x - p .* px;
    Hlx = Hlx / batch_size;
```
Instead of 
```
    p = vl_nnsoftmax(pred);  % softmaxed probabilities
    if ismatrix(p)
      px = sum(p .* x, 1);
    else  % 4D tensor
      px = sum(p .* x, 3);
    end
    % now finish computing Hl * x = diag(p) * x - p * p' * x
    Hlx = p .* x - p .* px;
    Hlx = Hlx / batch_size
```

Can you tell me if this fix works for you as well ?

**Comment by Yolanda-Gao** [comment]
Sorry, my bug is still there. 

What is your dimension of p, x and px running the first example of Cifar CNN? 

When I check in debug mode, the p and x are 1x1x10x128 and px is 1x1x1x128. So that p. * px cannot be computed. The px's third dimension is summed in former code. 

Thanks!

**Comment by hyenal** [comment]
I have the same dimensions. It should still work thanks to broadcasting (also known as implicit expansion in matlab). It is available for Matlab R2016b version and further. I'd suggest upgrading your matlab or the following fix:

```
    p = vl_nnsoftmax(pred);  % softmaxed probabilities
    Hlx = zeros(size(x), 'gpuArray');
    ptmp = squeeze(p);
    xtmp = squeeze(x);
    px = sum(ptmp .* xtmp, 1);
    %% now finish computing Hl * x = diag(p) * x - p * p' * x
    Hlx(1,1,:,:) = ptmp .* xtmp - ptmp .* px;
    Hlx = Hlx / batch_size;
```

**Comment by Yolanda-Gao** [comment]
Yes it is because of the implicit expansion of broadcasting. Thanks!!

I add pxtmp = repmat(px, size(xtmp,1)) and it works. (The fix you provided still doesn't work in 2016a as px and p are still not the same dimension.)

Thank you again for the help. I really appreciate it! :)

**Comment by hyenal** [comment]
Glad it helped :)
